variables:
  - group: gtc-rg-analytics-prod
  - template: common.yml
  - name: rgEnvironment
    value: 'Production'
  - name: rgName
    value: 'gtc-rg-analytics-prod-001'
  - name: rgLocation
    value: 'West US 2'
  - name: 'appiName'
    value: 'appi-analytics-prod-001'
  - name: 'kvName'
    value: 'kv-analytics-prod-001'
  - name: 'nugetFeeds'
    value: 'select'
  - name: 'nugetType'
    value: 'internal'
  - name: stName
    value: 'stanalyticsprod001'
  - name: workName
    value: 'work-analytics-prod-001'