variables:
  - group: gtc-rg-analytics-prod
  - template: common.yml  
  - name: rgEnvironment
    value: 'Production'
  - name: rgName
    value: 'gtc-rg-analytics-prod-225'
  - name: locationName
    value: 'West US 2'
  - name: 'appiName'
    value: 'appi-analytics-prod-225'
  - name: 'cogName'
    value: 'cog-analytics-prod-225'
  - name: cogsku
    value: 'S0'
  - name: cogtextName
    value: 'cogtext-analytics-prod-225'
  - name: cogtextSku
    value: 'S'
  - name: 'kvName'
    value: 'kv-analytics-prod-225'
  - name: 'nugetServiceConnection'
    value: 'gtc-nuget-prod-001'
  - name: 'nugetFeeds'
    value: 'select'
  - name: 'nugetType'
    value: 'external'
  - name: storageName
    value: 'stanalyticsprod225'
  - name: workspaceName
    value: 'work-analytics-prod-225'